name: Gramophone
options:
  bundleIdPrefix: com.traviswyatt
  usesTabs: false
  indentWidth: 4
  defaultConfig: Debug
targets:
  Gramophone:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      OTHER_LDFLAGS: "$(inherited) -framework ComposeApp"
      FRAMEWORK_SEARCH_PATHS: "$(SRCROOT)/../app/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)"
      ENABLE_BITCODE: "YES"
      ONLY_ACTIVE_ARCH: "NO"
      VALID_ARCHS: "arm64"
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      MARKETING_VERSION: 1
      CURRENT_PROJECT_VERSION: 1
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.traviswyatt.gramophone
      SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: NO
    resources:
      - path: Resources/Assets.xcassets
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: "Gramophone"
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
        UILaunchScreen:
          UIColorName: black
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSBluetoothAlwaysUsageDescription: Uses bluetooth for finding dictation host.
        NSContactsUsageDescription: Needed by dependency.
        NSLocationWhenInUseUsageDescription: Needed by dependency.
        NSMicrophoneUsageDescription: Uses microphone for dictation (speech-to-text).
        NSMotionUsageDescription: Needed by dependency.
        NSSpeechRecognitionUsageDescription: Uses speech recognition for dictation.
    sources:
      - path: Sources
        buildPhase: sources
      - path: Resources
        buildPhase: resources
    preBuildScripts:
      - script: |
          cd "$SRCROOT/.."
          ./gradlew :app:embedAndSignAppleFrameworkForXcode
