name: Gramophone
options:
  bundleIdPrefix: com.traviswyatt
  usesTabs: false
  indentWidth: 4
  defaultConfig: Debug
targets:
  Gramophone:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      MARKETING_VERSION: 1
      CURRENT_PROJECT_VERSION: 1
      GENERATE_INFOPLIST_FILE: YES
      PRODUCT_BUNDLE_IDENTIFIER: com.traviswyatt.gramophone
    resources:
      - path: Resources/Assets.xcassets
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: "Gramophone"
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
        UILaunchScreen:
          UIColorName: black
        NSMicrophoneUsageDescription: Uses microphone for dictation (speech-to-text).
        NSBluetoothAlwaysUsageDescription: Uses bluetooth for finding dictation host.
    sources:
      - path: Sources
        buildPhase: sources
      - path: Resources
        buildPhase: resources
    dependencies:
      - framework: ../app/build/bin/iosArm64/debugFramework/ComposeApp.framework
